// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'reader-figures-head-text'
  | 'reader-figures-refresh-button-tooltip'
  | 'reader-figures-sidenav-tooltip'
  | 'startup-begin'
  | 'startup-finish';
